service: expertise-rimac

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
  environment: ${file(env.${self:provider.stage}.json)}
  timeout: 30

custom:
  configpath: ./config

package:
  individually: true
  patterns:
    - "!.serverless/**"
    - "!.git/**"
    - "!*.md"
    - "!env.*.json"
    - '!node_modules/**'
    - '!package-lock.json'
layers:
  NodLayer:
    name: ${self:service}-${self:provider.stage}-dependencies
    path: layers
    description: "Node modules del expertise-talleres rimac"
    package:
      exclude:
        - "!nodejs/node_modules/**"

functions: ${file(${self:custom.configpath}/serverless/functions.yml)}

plugins:
  - serverless-offline