getDeduciblesText:
  handler: src/Deducible/controller.getDeduciblesText
  layers:
      - { Ref: NodLayerLambdaLayer }
  events:
    - http:
        method: get
        path: /deducibles/getText
        cors: ${file(${self:custom.configpath}/serverless/http-cors.yml)}
        response: ${file(${self:custom.configpath}/serverless/http-response.yml)}
getDeduciblesByText:
  handler: src/Deducible/controller.getDeduciblesByText
  layers:
      - { Ref: NodLayerLambdaLayer }
  events:
    - http:
        method: post
        path: /deducibles/byText
        cors: ${file(${self:custom.configpath}/serverless/http-cors.yml)}
        # response: ${file(${self:custom.configpath}/serverless/http-response.yml)}
getDistritos:
  handler: src/Distrito/controller.getDistritos
  layers:
      - { Ref: NodLayerLambdaLayer }
  events:
    - http:
        method: get
        path: /distritos/
        cors: ${file(${self:custom.configpath}/serverless/http-cors.yml)}
        response: ${file(${self:custom.configpath}/serverless/http-response.yml)}
buscarTaller:
  handler: src/Taller/controller.buscarTaller
  layers:
      - { Ref: NodLayerLambdaLayer }
  events:
    - http:
        method: get
        path: /taller/buscar
        cors: ${file(${self:custom.configpath}/serverless/http-cors.yml)}
        response: ${file(${self:custom.configpath}/serverless/http-response.yml)}

